### 데이터 확인

In [1]:
import pandas as pd

df = pd.read_csv('c:/3rd_project/data/Train/movie_data_230929.csv')
df

,img_name,airplane,apple,backpack,banana,baseball bat,baseball glove,bear,bed,bench,...,color_1_r,color_1_g,color_1_b,color_2_r,color_2_g,color_2_b,color_3_r,color_3_g,color_3_b,genre
0,잃어버린 마법의 섬 홋타라케,0,0,0,0,0,0,0,0,0,...,0.3882,0.6353,0.6980,0.3294,0.3294,0.2784,0.8392,0.8824,0.9020,애니메이션
1,극장판 메탈 베이블레이드 VS 태양 작열의 침략자 솔블레이즈,0,0,0,0,0,0,0,0,0,...,0.1961,0.1451,0.1804,0.6667,0.4039,0.3216,0.8000,0.7922,0.7725,애니메이션
2,동자 대소동,0,0,0,0,0,0,0,0,0,...,0.2824,0.1961,0.1373,0.9098,0.8275,0.7608,0.7059,0.4784,0.3373,코미디
3,내 친구의 소원,0,0,0,0,0,0,0,0,0,...,0.8275,0.3647,0.3137,0.9843,0.9686,0.9569,0.2863,0.2627,0.3216,코미디
4,러브 앤 댄싱,0,0,0,0,0,0,0,0,0,...,0.9137,0.7804,0.4431,0.3451,0.0627,0.0941,0.7451,0.4510,0.1569,드라마
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6010,붉은 사막,0,0,0,0,0,0,0,0,0,...,0.9020,0.6471,0.4902,0.1098,0.0863,0.0784,0.7529,0.1765,0.1255,드라마
6011,비닐하우스,0,0,0,0,0,0,0,0,0,...,0.4784,0.5059,0.7137,0.2471,0.2275,0.3569,0.0863,0.0706,0.1137,-
6012,에고이스트,0,0,0,0,0,0,0,0,0,...,0.0706,0.2118,0.3098,0.7294,0.6157,0.5333,0.0510,0.1020,0.1216,드라마
6013,핑크퐁 시네마 콘서트3 : 진저브레드맨을 잡아라,0,0,0,0,0,0,0,0,0,...,0.3412,0.8196,0.9569,0.8902,0.7725,0.7843,0.4824,0.2824,0.1529,애니메이션
6014,헌티드 맨션,0,0,0,0,0,0,0,0,0,...,0.0510,0.0314,0.0980,0.2392,0.2196,0.4078,0.4314,0.6157,0.8392,공포(호러)

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6015 entries, 0 to 6014
Data columns (total 93 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   img_name        6015 non-null   object
 1   airplane        6015 non-null   int64
 2   apple           6015 non-null   int64
 3   backpack        6015 non-null   int64
 4   banana          6015 non-null   int64
 5   baseball bat    6015 non-null   int64
 6   baseball glove  6015 non-null   int64
 7   bear            6015 non-null   int64
 8   bed             6015 non-null   int64
 9   bench           6015 non-null   int64
 10  bicycle         6015 non-null   int64
 11  bird            6015 non-null   int64
 12  boat            6015 non-null   int64
 13  book            6015 non-null   int64
 14  bottle          6015 non-null   int64
 15  bowl            6015 non-null   int64
 16  broccoli        6015 non-null   int64
 17  bus             6015 non-null   int64
 18  cake            6015 non-null   int64
 19  car             6015 non-null   int64
 20  carrot          6015 non-null   int64
 21  cat             6015 non-null   int64
 22  cell phone      6015 non-null   int64
 23  chair           6015 non-null   int64
 24  clock           6015 non-null   int64
 25  couch           6015 non-null   int64
 26  cow             6015 non-null   int64
 27  cup             6015 non-null   int64
 28  dining table    6015 non-null   int64
 29  dog             6015 non-null   int64
 30  donut           6015 non-null   int64
 31  elephant        6015 non-null   int64
 32  fire hydrant    6015 non-null   int64
 33  fork            6015 non-null   int64
 34  frisbee         6015 non-null   int64
 35  giraffe         6015 non-null   int64
 36  hair drier      6015 non-null   int64
 37  handbag         6015 non-null   int64
 38  horse           6015 non-null   int64
 39  hot dog         6015 non-null   int64
 40  keyboard        6015 non-null   int64
 41  kite            6015 non-null   int64
 42  knife           6015 non-null   int64
 43  laptop          6015 non-null   int64
 44  microwave       6015 non-null   int64
 45  motorcycle      6015 non-null   int64
 46  mouse           6015 non-null   int64
 47  orange          6015 non-null   int64
 48  oven            6015 non-null   int64
 49  parking meter   6015 non-null   int64
 50  person          6015 non-null   int64
 51  pizza           6015 non-null   int64
 52  potted plant    6015 non-null   int64
 53  refrigerator    6015 non-null   int64
 54  remote          6015 non-null   int64
 55  sandwich        6015 non-null   int64
 56  scissors        6015 non-null   int64
 57  sheep           6015 non-null   int64
 58  sink            6015 non-null   int64
 59  skateboard      6015 non-null   int64
 60  skis            6015 non-null   int64
 61  snowboard       6015 non-null   int64
 62  spoon           6015 non-null   int64
 63  sports ball     6015 non-null   int64
 64  stop sign       6015 non-null   int64
 65  suitcase        6015 non-null   int64
 66  surfboard       6015 non-null   int64
 67  teddy bear      6015 non-null   int64
 68  tennis racket   6015 non-null   int64
 69  tie             6015 non-null   int64
 70  toaster         6015 non-null   int64
 71  toilet          6015 non-null   int64
 72  toothbrush      6015 non-null   int64
 73  traffic light   6015 non-null   int64
 74  train           6015 non-null   int64
 75  truck           6015 non-null   int64
 76  tv              6015 non-null   int64
 77  umbrella        6015 non-null   int64
 78  vase            6015 non-null   int64
 79  wine glass      6015 non-null   int64
 80  zebra           6015 non-null   int64
 81  gun             6015 non-null   int64
 82  brightness      6015 non-null   float64
 83  color_1_r       6015 non-null   float64
 84  color_1_g       6015 non-null   float64
 85  color_1_b       6015 non-null   float64
 86  color_2_r       6015 non-null   float64
 87  color_2_g       6015 non-null   float64
 88  color_2_b       6015 non-null   float64
 89  color_3_r       6015 non-null   float64
 90  color_3_g       6015 non-null   float64
 91  color_3_b       6015 non-null   float64
 92  genre           6015 non-null   object
dtypes: float64(10), int64(81), object(2)
memory usage: 4.3+ MB

In [3]:
df['genre'].value_counts()

genre
드라마       1763
-         1299
액션        1218
코미디        699
애니메이션      657
공포(호러)     379
Name: count, dtype: int64

In [4]:
# 장르 라벨링

from sklearn.preprocessing import LabelEncoder

# LabelEncoder 객체 생성
label_encoder = LabelEncoder()

print(df['genre'].unique())

# 'genre' 열을 라벨링하여 새로운 'label_genre' 열 생성
df['genre'] = label_encoder.fit_transform(df['genre'])
print(df['genre'].unique())

df

['애니메이션' '코미디' '드라마' '액션' '-' '공포(호러)']
[3 5 2 4 0 1]

,img_name,airplane,apple,backpack,banana,baseball bat,baseball glove,bear,bed,bench,...,color_1_r,color_1_g,color_1_b,color_2_r,color_2_g,color_2_b,color_3_r,color_3_g,color_3_b,genre
0,잃어버린 마법의 섬 홋타라케,0,0,0,0,0,0,0,0,0,...,0.3882,0.6353,0.6980,0.3294,0.3294,0.2784,0.8392,0.8824,0.9020,3
1,극장판 메탈 베이블레이드 VS 태양 작열의 침략자 솔블레이즈,0,0,0,0,0,0,0,0,0,...,0.1961,0.1451,0.1804,0.6667,0.4039,0.3216,0.8000,0.7922,0.7725,3
2,동자 대소동,0,0,0,0,0,0,0,0,0,...,0.2824,0.1961,0.1373,0.9098,0.8275,0.7608,0.7059,0.4784,0.3373,5
3,내 친구의 소원,0,0,0,0,0,0,0,0,0,...,0.8275,0.3647,0.3137,0.9843,0.9686,0.9569,0.2863,0.2627,0.3216,5
4,러브 앤 댄싱,0,0,0,0,0,0,0,0,0,...,0.9137,0.7804,0.4431,0.3451,0.0627,0.0941,0.7451,0.4510,0.1569,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6010,붉은 사막,0,0,0,0,0,0,0,0,0,...,0.9020,0.6471,0.4902,0.1098,0.0863,0.0784,0.7529,0.1765,0.1255,2
6011,비닐하우스,0,0,0,0,0,0,0,0,0,...,0.4784,0.5059,0.7137,0.2471,0.2275,0.3569,0.0863,0.0706,0.1137,0
6012,에고이스트,0,0,0,0,0,0,0,0,0,...,0.0706,0.2118,0.3098,0.7294,0.6157,0.5333,0.0510,0.1020,0.1216,2
6013,핑크퐁 시네마 콘서트3 : 진저브레드맨을 잡아라,0,0,0,0,0,0,0,0,0,...,0.3412,0.8196,0.9569,0.8902,0.7725,0.7843,0.4824,0.2824,0.1529,3
6014,헌티드 맨션,0,0,0,0,0,0,0,0,0,...,0.0510,0.0314,0.0980,0.2392,0.2196,0.4078,0.4314,0.6157,0.8392,1

In [5]:
df['genre'].value_counts()

# 드라마    2
# -         0
# 액션      4
# 코미디    5
# 애니      3
# 공포      1

genre
2    1763
0    1299
4    1218
5     699
3     657
1     379
Name: count, dtype: int64

### 언더샘플링

In [6]:
RANDOM_STATE = 2023

In [7]:
train_cols = df.columns[1:-1]

X = df[train_cols]
y = df['genre']

from imblearn.under_sampling import RandomUnderSampler

X_sample, y_sample = RandomUnderSampler(random_state=RANDOM_STATE).fit_resample(X, y)
X_samp = pd.DataFrame(data=X_sample,columns=train_cols )
y_samp = pd.DataFrame(data=y_sample,columns=['genre'])

data_samp=pd.concat([X_samp,y_samp],axis=1)

data_samp["genre"].value_counts()

genre
0    379
1    379
2    379
3    379
4    379
5    379
Name: count, dtype: int64

In [8]:
data_samp

,airplane,apple,backpack,banana,baseball bat,baseball glove,bear,bed,bench,bicycle,...,color_1_r,color_1_g,color_1_b,color_2_r,color_2_g,color_2_b,color_3_r,color_3_g,color_3_b,genre
3512,0,0,0,0,0,0,0,0,0,0,...,0.6235,0.5961,0.5961,0.0314,0.0314,0.0314,0.8863,0.8824,0.8824,0
3970,0,0,0,0,0,0,0,0,0,0,...,0.4980,0.3647,0.4706,0.0706,0.0431,0.0549,0.9176,0.7922,0.5373,0
1250,0,0,0,0,0,0,0,0,0,0,...,0.5647,0.6392,0.7216,0.8941,0.9020,0.9059,0.1686,0.1686,0.1765,0
1641,0,0,0,0,0,0,0,0,0,0,...,0.0980,0.0745,0.0588,0.8392,0.7647,0.7255,0.5020,0.4157,0.3765,0
4382,0,0,0,0,0,0,0,0,0,0,...,0.1843,0.1216,0.1529,0.8235,0.8039,0.7804,0.0275,0.0941,0.1490,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3575,0,0,0,0,0,0,0,0,0,0,...,0.5922,0.6353,0.6431,0.8314,0.8471,0.8196,0.1451,0.1882,0.2392,5
4740,0,0,0,0,0,0,0,0,0,0,...,0.9922,0.9922,0.9922,0.2863,0.2824,0.2745,0.7647,0.5922,0.4471,5
1844,0,0,0,0,0,0,0,0,0,0,...,0.7373,0.6196,0.5608,0.2588,0.1804,0.1686,0.9216,0.8784,0.8510,5
4173,0,0,0,0,0,0,0,0,0,0,...,0.8353,0.7804,0.7569,0.1373,0.1020,0.1333,0.5255,0.3333,0.3294,5
1838,0,0,0,0,0,0,0,0,0,0,...,0.0824,0.0314,0.0784,0.8784,0.8549,0.8039,0.6118,0.2471,0.1569,5

In [9]:
X = data_samp.iloc[:, :-1].values
y = data_samp.iloc[:, -1].values

In [10]:
X

array([[0.    , 0.    , 0.    , ..., 0.8863, 0.8824, 0.8824],
       [0.    , 0.    , 0.    , ..., 0.9176, 0.7922, 0.5373],
       [0.    , 0.    , 0.    , ..., 0.1686, 0.1686, 0.1765],
       ...,
       [0.    , 0.    , 0.    , ..., 0.9216, 0.8784, 0.851 ],
       [0.    , 0.    , 0.    , ..., 0.5255, 0.3333, 0.3294],
       [0.    , 0.    , 0.    , ..., 0.6118, 0.2471, 0.1569]])

In [11]:
y

array([0, 0, 0, ..., 5, 5, 5])

In [12]:
data_samp

,airplane,apple,backpack,banana,baseball bat,baseball glove,bear,bed,bench,bicycle,...,color_1_r,color_1_g,color_1_b,color_2_r,color_2_g,color_2_b,color_3_r,color_3_g,color_3_b,genre
3512,0,0,0,0,0,0,0,0,0,0,...,0.6235,0.5961,0.5961,0.0314,0.0314,0.0314,0.8863,0.8824,0.8824,0
3970,0,0,0,0,0,0,0,0,0,0,...,0.4980,0.3647,0.4706,0.0706,0.0431,0.0549,0.9176,0.7922,0.5373,0
1250,0,0,0,0,0,0,0,0,0,0,...,0.5647,0.6392,0.7216,0.8941,0.9020,0.9059,0.1686,0.1686,0.1765,0
1641,0,0,0,0,0,0,0,0,0,0,...,0.0980,0.0745,0.0588,0.8392,0.7647,0.7255,0.5020,0.4157,0.3765,0
4382,0,0,0,0,0,0,0,0,0,0,...,0.1843,0.1216,0.1529,0.8235,0.8039,0.7804,0.0275,0.0941,0.1490,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3575,0,0,0,0,0,0,0,0,0,0,...,0.5922,0.6353,0.6431,0.8314,0.8471,0.8196,0.1451,0.1882,0.2392,5
4740,0,0,0,0,0,0,0,0,0,0,...,0.9922,0.9922,0.9922,0.2863,0.2824,0.2745,0.7647,0.5922,0.4471,5
1844,0,0,0,0,0,0,0,0,0,0,...,0.7373,0.6196,0.5608,0.2588,0.1804,0.1686,0.9216,0.8784,0.8510,5
4173,0,0,0,0,0,0,0,0,0,0,...,0.8353,0.7804,0.7569,0.1373,0.1020,0.1333,0.5255,0.3333,0.3294,5
1838,0,0,0,0,0,0,0,0,0,0,...,0.0824,0.0314,0.0784,0.8784,0.8549,0.8039,0.6118,0.2471,0.1569,5

### 데이터 셋 나누기

In [13]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, test_size=0.2, random_state=RANDOM_STATE)

In [14]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# 랜덤 포레스트 모델 생성
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)

# 모델 훈련
rf_classifier.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [18]:
# 모델 평가
y_pred = rf_classifier.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {round(accuracy,4)}')

Accuracy: 0.3736

In [17]:
# 새로운 데이터에 대한 예측
num = [885, 3925, 1732, 409, 486, 551]

for i in num:

    real_genre = df.iloc[i][-1]
    new_data = df.iloc[i][1:-1].values  # Pandas Series를 NumPy 배열로 변환
    new_data = new_data.reshape(1, -1)  # 2D 배열로 변환
    predicted_genre = rf_classifier.predict(new_data)

    print(f'실제 장르: {real_genre}')
    print(f'예측 장르: {predicted_genre}\n')

실제 장르: 0
예측 장르: [1]

실제 장르: 1
예측 장르: [1]

실제 장르: 2
예측 장르: [4]

실제 장르: 3
예측 장르: [3]

실제 장르: 4
예측 장르: [5]

실제 장르: 5
예측 장르: [2]

In [ ]:
# 드라마    2       1905
# -         0       3662
# 액션      4       4849
# 코미디    5       5209
# 애니      3       5848
# 공포      1       274